name: build-and-test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
         python-version: '3.12'
      - name: Install dependencies
        run: |
         python -m pip install --upgrade pip
         pip install -r requirements.txt
      - name: Lint with black
        run: black . --check --diff --color
      - name: Check types
        run: mypy -m tests
      - name: Run tests
        run: |
          python -m unittest discover -s tests