name: Check code and run tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
         python-version: '3.12'
      - name: Install Poetry
        run: |
         python -m pip install --upgrade pip
         pip install poetry

      - name: Install dependencies
        run: |
          poetry install

      - name: Lint with black
        run: poetry run black . --check --diff --color

      - name: Install pre-commit
        run: |
          poetry run pre-commit install
          poetry run pre-commit run --all-files --color always --verbose --show-diff-on-failure

      - name: Check types
        run: poetry run mypy -m tests

      - name: Run tests
        run: |
         poetry run python -m pytest tests
